"""The self-extractor script template.

`encoder.render_script` substitutes the ``{{PLACEHOLDER}}`` tokens below with the
concrete payload/metadata for a given file. The rendered result is a standalone,
stdlib-only Python program (runs on Python 3.8+) that reconstructs the original file.

Tokens are replaced via plain string substitution (not ``str.format``), so the
template body may freely contain ``{`` / ``}`` and ``%`` characters.
"""

# Tokens substituted by the encoder.
TOKEN_FILENAME = "{{FILENAME}}"
TOKEN_COMPRESSED = "{{COMPRESSED}}"
TOKEN_SHA256 = "{{SHA256}}"
TOKEN_SIZE = "{{SIZE}}"
TOKEN_SOURCE = "{{SOURCE}}"
TOKEN_PAYLOAD = "{{PAYLOAD}}"

TEMPLATE = '''#!/usr/bin/env python3
"""Self-extracting archive generated by zencoded.

Running this script reconstructs the original file in the current directory,
verifying its SHA-256 checksum. Standard library only; no dependencies.

    python {{FILENAME}}.py            # write ./{{FILENAME}}
    python <thisfile> --force         # overwrite an existing target
    python <thisfile> -o DIR          # write into DIR instead of the cwd
    python <thisfile> --stdout        # write raw bytes to stdout
"""
import argparse
import base64
import gzip
import hashlib
import sys
from pathlib import Path

FILENAME = "{{FILENAME}}"
COMPRESSED = {{COMPRESSED}}
SHA256 = "{{SHA256}}"
SIZE = {{SIZE}}
SOURCE = {{SOURCE}}
PAYLOAD = """
{{PAYLOAD}}
"""


def extract_bytes():
    """Return the original file's bytes, verifying the embedded checksum."""
    # b64decode ignores the embedded newlines (non-alphabet chars) by default.
    raw = base64.b64decode(PAYLOAD)
    data = gzip.decompress(raw) if COMPRESSED else raw
    digest = hashlib.sha256(data).hexdigest()
    if digest != SHA256:
        raise SystemExit(
            "checksum mismatch: expected {expected}, got {actual}".format(
                expected=SHA256, actual=digest
            )
        )
    return data


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Extract the file embedded in this self-extractor."
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        default=".",
        help="directory to write the extracted file into (default: current dir)",
    )
    parser.add_argument(
        "-f",
        "--force",
        action="store_true",
        help="overwrite the target file if it already exists",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="write the raw bytes to stdout instead of a file",
    )
    args = parser.parse_args(argv)

    data = extract_bytes()

    if args.stdout:
        sys.stdout.buffer.write(data)
        return 0

    target = Path(args.output_dir) / FILENAME
    if target.exists() and not args.force:
        raise SystemExit(
            "refusing to overwrite existing file: {target} (use --force)".format(
                target=target
            )
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(data)
    print("wrote {target} ({size} bytes)".format(target=target, size=len(data)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''
